export enum MessageId {
    DTM = 'DTM',
    GBQ = 'GBQ',
    GBS = 'GBS',
    GGA = 'GGA',
    GLL = 'GLL',
    GLQ = 'GLQ',
    GNQ = 'GNQ',
    GNS = 'GNS',
    GPQ = 'GPQ',
    GRS = 'GRS',
    GSA = 'GSA',
    GST = 'GST',
    GSV = 'GSV',
    RMC = 'RMC',
    TXT = 'TXT',
    VLW = 'VLW',
    VTG = 'VTG',
    ZDA = 'ZDA'
}
